### ISSUE TITLE
[Bug] Plugin v0.3.2 fails to load

### ISSUE THREAD

**Issue by xe1os** [killerbigpoint/cs2-anticheat#5]
@killerbigpoint unable to load plugin v0.3.2 on CS2 server hosted on Windows.

But v0.1.0 was loading without any errors.

![image](https://github.com/killerbigpoint/cs2-anticheat/assets/39219862/a75a30fe-fb68-4e72-9d4a-1c8423fd32c4)

**Comment by asapverneri** [comment]
Same issue

**Comment by killerbigpoint** [comment]
Thank you for reporting it. This is fixed now
